### ISSUE TITLE
what should i do

### ISSUE THREAD

**Issue by SeanBeansShako** [elmoiv/pubg_no_recoil#1]
hello bro i installed python , pyautogui and pywin32
i open file then enter shift amount shown but i don't know what should i do 
can u explain how can i use file 
thanks

**Comment by elmoiv** [comment]
Ok, just wait.
I am writing a Readme. I will mention you when I upload first release

**Comment by elmoiv** [comment]
You can download first release from here:
https://github.com/elmoiv/pubg_no_recoil/releases/tag/1.0
